// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_HBrpq4xZOYRI3f9HmWsr79fZKD7KN3Q',
    appId: '1:237039324020:web:03cb159faa8d8818b43a21',
    messagingSenderId: '237039324020',
    projectId: 'cookbookpro-49c6d',
    authDomain: 'cookbookpro-49c6d.firebaseapp.com',
    storageBucket: 'cookbookpro-49c6d.appspot.com',
    measurementId: 'G-7HZJ36GWZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JbCbuKB8151hpIJDI-3OlsYfl3E9zKI',
    appId: '1:237039324020:android:ab873d1f6d9fce2fb43a21',
    messagingSenderId: '237039324020',
    projectId: 'cookbookpro-49c6d',
    storageBucket: 'cookbookpro-49c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZqYRvrYPBEtZrbg3vgtolog6z_F499ZY',
    appId: '1:237039324020:ios:ba92db15d4b95df4b43a21',
    messagingSenderId: '237039324020',
    projectId: 'cookbookpro-49c6d',
    storageBucket: 'cookbookpro-49c6d.appspot.com',
    iosBundleId: 'com.example.cookbookpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZqYRvrYPBEtZrbg3vgtolog6z_F499ZY',
    appId: '1:237039324020:ios:ba92db15d4b95df4b43a21',
    messagingSenderId: '237039324020',
    projectId: 'cookbookpro-49c6d',
    storageBucket: 'cookbookpro-49c6d.appspot.com',
    iosBundleId: 'com.example.cookbookpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_HBrpq4xZOYRI3f9HmWsr79fZKD7KN3Q',
    appId: '1:237039324020:web:2723d50b9324f52cb43a21',
    messagingSenderId: '237039324020',
    projectId: 'cookbookpro-49c6d',
    authDomain: 'cookbookpro-49c6d.firebaseapp.com',
    storageBucket: 'cookbookpro-49c6d.appspot.com',
    measurementId: 'G-WN473BBQVE',
  );
}
